name: pipeline
channels:
    - defaults
    - conda-forge
dependencies:
    - python==3.6.*
    - pydantic
    - scikit-learn
    - redis-py
    - redis
    - pandas
    - numpy
    - jupyterlab
    - pytest
    - pip
    - pip:
      - -e .
      - parsl
